Vitaly/feature/sort and date
Simple2B/flora pull request #39
Opened 2020-11-18 11:34 UTC by Ziles131

1. Add date_time to biddings-table in td named Due Date
2. Add two fields in bid-model
3. Create Sort to bids by date

2020-11-18 12:55 UTC, kipod requested changes
Please correct logic with date_today

2020-11-18 12:55 UTC, kipod commented on app/models/bid.py
> +date_today = datetime.datetime.today().strftime("%m/%d/%Y")
эта переменная будет посчитана один раз при загрузке модуля
и её значение останется неизменным пока модуль до следущего рестарта системы

2020-11-18 14:35 UTC, Ziles131 commented on app/models/bid.py
> +date_today = datetime.datetime.today().strftime("%m/%d/%Y")
насколько я понимаю, оно будет пересчитываться при каждом сохранении бида, правильно? Если так, то все вроде окей, потому что если бид не менялся, то значение у него останется дефолтным, но при изменении бида, тут же поменяется и это поле

2020-11-18 17:01 UTC, kipod requested changes

2020-11-18 17:01 UTC, kipod commented on app/models/bid.py
> +date_today = datetime.datetime.today().strftime("%m/%d/%Y")
нет. Не правильно. Подумай и исправляй.

2020-11-24 16:05 UTC, kipod approved these changes

2020-11-24 16:05 UTC, kipod commented on app/models/bid.py
> +    last_updated = db.Column(db.String(256), default=date(), nullable=False)
last_updated = db.Column(db.String(256), default=date, nullable=False)

2020-11-26 15:50 UTC, kipod approved these changes

2020-11-26 15:50 UTC, kipod commented on app/models/bid.py
> +    last_updated = db.Column(db.String(256), default=(lambda: datetime.today().strftime("%m/%d/%Y"))(), nullable=False)
256 -> 16. для этой строки достаточно 16 символов

2020-11-26 15:50 UTC, kipod commented on app/views/bid.py
> +        bid.save()
раз

2020-11-26 15:50 UTC, kipod commented on app/views/bid.py
> +                    bid.save()
два

2020-11-26 15:50 UTC, kipod commented on app/views/bid.py
> +                    bid.save()
три

2020-11-26 15:50 UTC, kipod commented on app/views/bid.py
> +            bid.save()
четыре

2020-11-26 15:50 UTC, kipod commented on app/views/bid.py
> +            bid.save()
пять

2020-11-26 15:50 UTC, kipod commented on app/views/bid.py
> +            bid.save()
шесть

2020-11-26 15:50 UTC, kipod commented on app/views/bid.py
> +            bid.save()
семь

2020-11-26 15:50 UTC, kipod commented on app/views/work_item.py
> +        bid.save()
восемь!!! Восемь раз одно и то же. This is code duplication. What about refactoring it as one function?

2020-11-29 08:43 UTC, merged